name: CI/CD Pipeline with Runner ID

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Print Runner Info
        run: |
          echo "Running on GitHub runner ID: ${{ github.run_id }} with name ${{ runner.name }}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          IMAGE_TAG=${{ github.run_id }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/notes-app:$IMAGE_TAG .

      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/notes-app:$IMAGE_TAG

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Print Runner Info
        run: | 
           echo "Testing on GitHub runner ID: ${{ github.run_id }} with name ${{ runner.name }}"

      - name: Run Tests
        run: echo "This is testing the code"
