name: CI/CD Pipeline

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract Git Commit SHA
        id: vars
        run: echo "SHA_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ vars.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Tag Docker Image
        run: |
          docker build -t ${{ vars.DOCKER_USERNAME }}/notes-app:${{ env.SHA_TAG }} .
          docker tag ${{ vars.DOCKER_USERNAME }}/notes-app:${{ env.SHA_TAG }} ${{ vars.DOCKER_USERNAME }}/notes-app:latest

      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ vars.DOCKER_USERNAME }}/notes-app:${{ env.SHA_TAG }}
          docker push ${{ vars.DOCKER_USERNAME }}/notes-app:latest

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test
