name: CI Part

on: push

jobs:
  build-job-1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ vars.DOCKER_USERNAME }}" --password-stdin
        
      - name: Build and Push Docker Image
        run: |
          BRANCH_NAME=$(echo ${{ github.ref_name }} | sed 's/\//-/g')
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          IMAGE_TAG=${{ github.run_number }}-${BRANCH_NAME}-${TIMESTAMP}
          docker build -t ${{ vars.DOCKER_USERNAME }}/notes-app:$IMAGE_TAG .
          docker push ${{ vars.DOCKER_USERNAME }}/notes-app:$IMAGE_TAG

  test-job-2:
    runs-on: ubuntu-latest
    needs: build-job-1

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Run Tests
        run: echo "This is testing the code"

