name: CI/CD Pipeline for Sample application

on: push

jobs:
  build-job-1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: docker build -t notes-tech:latest -t ${{ vars.DOCKER_USERNAME }}/notes-tech:latest .

      - name: Login to Docker Hub
        run: docker login -u "${{ vars.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"

      - name: Give the image tag
        run: docker image tag notes-tech:latest "${{ vars.DOCKER_USERNAME }}"/notes-tech:latest
      
      - name: Push Docker Image
        run: docker push "${{ vars.DOCKER_USERNAME }}"/notes-tech:latest

  test-job-2:
    runs-on: ubuntu-latest
    needs: build-job-1

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Tests
        run: echo "This is testing the code"
        
