name: CI/CD Pipeline

on: push

jobs:
  job-1-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        run: echo "${{ vars.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t notes-app:latest .

  job-2-test:
    runs-on: ubuntu-latest
    needs: job-1-build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Tests
        run: echo "This is testing the code"

  job-3-deploy:
    runs-on: ubuntu-latest
    needs: job-2-test

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy Application
        run: |
          docker run -d -p 8000:8000 notes-app:latest
